[package]
name = "nanocraft"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1"
ogl33 = { version = "0.2", features = ["debug_error_checks"] }
ultraviolet = "0.7"
nalgebra = "0.32.5"
glfw = "0.56.0"
imagine = "0.0.5"
femtovg = "0.9.1"
gl = "0.14.0"
image = "0.25.1"
